batch_size: 16
data_root: /media/juneyonglee/My Book/Preprocessed/UST21/test
gpu_ids: [0, 1]
land_sea_mask_path: /home/juneyonglee/Desktop/AY_ust/preprocessing/Land_mask/Land_mask.npy
mask_mode: 2
mask_root: /media/juneyonglee/My Book/Preprocessed/UST21/mask/test/10
result_save_path_default: /media/juneyonglee/My Book/results/10
max_epochs: null
model_path: /home/juneyonglee/MyData/5th_years/ust21_chl_8day/g_1000000.pth
model_save_path: null
n_threads: 6
num_iters: 1000000
num_workers: 16
target_size: 256
warmup_batchs: 1500
## python model/run.py --c configs/eval.yaml --test
