batch_size: 1
data_root: /media/juneyonglee/My Book/Preprocessed/GOCI/L2_Rrs_newtest/band_4/test
gpu_ids:
- 0
- 1
land_sea_mask_path: /home/juneyonglee/Desktop/AY_ust/preprocessing/is_land_on_GOCI.npy
mask_mode: 2
mask_root: /media/juneyonglee/My Book/data/mask/Test/50
max_epochs: null
model_path: model/models/GOCI_RRS_band4/g_550000.pth
model_save_path: null
n_threads: 6
num_iters: 800000
num_workers: 16
target_size: 256
warmup_batchs: 1500
