project_name: RFR
exp_name: CHL_0to20_ver2
notes: chl_4 resume from 2205000

data_root: /media/juneyonglee/My Book/data/Chl-a/train/perfect
mask_root: /media/juneyonglee/My Book/data/mask/Train
model_save_path: model/models/ust_chl_5
model_path: model/models/ust_chl_4/g_2200000.pth

max_epochs: ~
mask_mode: 0
batch_size: 16
target_size: 256
num_iters: 800000
n_threads: 6
gpu_ids: [0, 1]
save_capacity: 30

num_workers: 2
warmup_batchs: 1500S
