project_name: chl-a
exp_name: CHL_0to21_ver2
notes: chl_1

data_root: /media/juneyonglee/My Book/data/Chl-a/train/perfect
mask_root: /media/juneyonglee/My Book/data/mask/Train
# model_save_path: model/models/ust_chl_4
model_save_path: /home/juneyonglee/MyData/backup_20240722/AY_ust/model/models/ust_chl_4
model_path: model/models/ust_chl_4/g_466700.pth

max_epochs: ~
mask_mode: 0
batch_size: 32
target_size: 256
num_iters: 800000
n_threads: 6
gpu_ids: [0, 1]
save_capacity: 10

num_workers: 2
warmup_batchs: 1500S
