### python model/run.py --c configs/train.yaml

# project_name: chl-a
# exp_name: UST21_CHL_8day
# notes: chl_1

# data_root: /media/juneyonglee/My Book/Preprocessed/UST/Chl-a_8day/train
# mask_root: /media/juneyonglee/My Book/data/mask/Train
# model_save_path: /home/juneyonglee/MyData/backup_20240914/AY_UST/ust21_chl_8day
# # model_path: model/models/ust_chl_4/g_600000.pth
# model_path: /home/juneyonglee/MyData/backup_20240914/AY_UST/ust21_chl_8day/
# land_sea_mask_path: /home/juneyonglee/Desktop/AY_ust/preprocessing/Land_mask/Land_mask.npy

# # Training parameters
# max_epochs: ~
# mask_mode: 0
# batch_size: 32
# target_size: 256
# num_iters: 800000
# n_threads: 6
# gpu_ids: [0, 1]
# save_capacity: 5
# num_workers: 16
# warmup_batches: 1500  

# GOCI 
project_name: RRS
exp_name: GOCI RRS time data train
notes: GOCI RRS

# data_root: /home/juneyonglee/gocirrs_backup/home/pmilab/Documents/preprocessed_data/GOCI/Chl-a_processed/train/band_3
data_root: /media/juneyonglee/My Book/Preprocessed/GOCI/L2_Rrs_newtrain/band_2
mask_root: /media/juneyonglee/My Book/data/mask/Train
model_save_path: /home/juneyonglee/MyData/backup_20240914/AY_UST/GOCI_RRS_band2_newtrain
model_path: /home/juneyonglee/MyData/backup_20240914/AY_UST/GOCI_RRS_band2_newtrain
land_sea_mask_path: /home/juneyonglee/Desktop/AY_ust/preprocessing/is_land_on_GOCI.npy

# Training parameters
max_epochs: ~
mask_mode: 0
batch_size: 32
target_size: 256
num_iters: 800000
n_threads: 6
gpu_ids: [0, 1]
save_capacity: 5
num_workers: 16
warmup_batches: 1500  
