project_name: RFR
exp_name: CHL_only_range2
notes: 0~20 in range, else outlier

data_path: model/results/band_3_loss_10/550000/10
  # model/results/band_3_loss_10/550000/10

  # model/results/ust21_chl_8day_perfect/600000/10
  # model/results/ust21_chl_8day_perfect/600000/20
  # model/results/ust21_chl_8day_perfect/600000/30
  # model/results/ust21_chl_8day_perfect/600000/40
  # model/results/ust21_chl_8day_perfect/600000/50

#  60 example
#  model/results/ust_chl_4_perfect/600000/60
# land_sea_mask_path: /home/juneyonglee/Desktop/AY_ust/preprocessing/Land_mask/Land_mask.npy
land_sea_mask_path: /home/juneyonglee/Desktop/AY_ust/preprocessing/is_land_on_GOCI.npy

save_path: model/performance/band_3_loss_10
gpu_ids: [0, 1]

# python model/run.py --c configs/val.yaml --val
